"""Package details."""

__version__ = "0.4.0dev"
__docs__ = "Deprecation tooling"
__author__ = "Jiri Borovec"
__author_email__ = "j.borovec+github[at]gmail.com"
__homepage__ = "https://borda.github.io/pyDeprecate"
__source_code__ = "https://github.com/Borda/pyDeprecate"
__license__ = "Apache-2.0"
__copyright__ = f"Copyright (C) 2020-2025 {__author__}."
