site_name: pyDeprecate – Docstring Style Demo
docs_dir: docs

theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.code.annotate
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - . # demo.py lives here
            - ../src # deprecate package
          options:
            show_source: false
            show_root_heading: true
            docstring_style: google
            extensions:
              - deprecate._griffe_ext:RuntimeDocstrings
