name: Create Package

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: ""
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  package:
    runs-on: ${{ inputs.os }}

    steps:
      - name: 🔀 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 🐍 Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: 🔍 Pre-build pkg check
        run: |
          pip install check-manifest
          check-manifest
          python setup.py check --metadata --strict

      - name: 🏗️ Create package
        run: |
          pip install build
          python -m build

      - name: ✅ Verify package
        run: |
          pip install twine
          twine check dist/*

      - name: 📤 Upload artifact
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/
