name: Create Package

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: ""
      os:
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  package:
    runs-on: ${{ inputs.os }}

    steps:
      - name: 🔀 Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: 🐍 Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: 🔍 Pre-build pkg check
        run: |
          pip install check-manifest
          check-manifest
          python setup.py check --metadata --strict

      - name: 🏗️ Create package
        run: |
          pip install build
          python -m build

      - name: ✅ Verify package
        run: |
          pip install twine
          twine check dist/*

      - name: 📤 Upload artifact
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/
